const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
  SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

  //user
  ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  PROCESS_LOGOUT: 'PROCESS_LOGOUT',
  OAUTH2_DATA: 'OAUTH2_DATA',
  CHANGE_SIDEBAR_LG: 'CHANGE_SIDEBAR_LG',
  CHANGE_SIDEBAR_MODAL: 'CHANGE_SIDEBAR_MODAL',
  HIDEN_SIBAR_MINI: 'HIDEN_SIBAR_MINI',

  // admin
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  FETCH_USER_FAIL: 'FETCH_USER_FAIL',
  FETCH_CHANEL_SUCCESS: 'FETCH_CHANEL_SUCCESS',
  FETCH_CHANNEL_FAIL: 'FETCH_CHANNEL_FAIL',

  // video
  GET_VIDEO_SUCCESS: 'GET_VIDEO_SUCCESS',
  GET_VIDEO_FALSE: 'GET_VIDEO_FALSE',
  SEARCH_VIDEO_SUCCESS: 'SEARCH_VIDEO_SUCCESS',
  SEARCH_VIDEO_FALSE: 'SEARCH_VIDEO_FALSE',
  SHORT_VIDEO_SUCCESS: 'SHORT_VIDEO_SUCCESS',
  SHORT_VIDEO_FALSE: 'SHORT_VIDEO_FALSE',
  IS_SPINNER: 'IS_SPINNER',
  IS_LOADING_BAR: 'IS_LOADING_BAR',
});

export default actionTypes;
