const actionTypes = Object.freeze({
  //app =========
  APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
  SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  CHANGE_SIDEBAR_MINI: 'CHANGE_SIDEBAR_MINI',
  CHANGE_SIDEBAR_MODAL: 'CHANGE_SIDEBAR_MODAL',
  HIDEN_SIBAR_MINI: 'HIDEN_SIBAR_MINI',
  CHANGE_THEME_MODE: 'CHANGE_THEME_MODE',

  //user =========
  SET_LOGGED_IN: 'SET_LOGGED_IN',
  PROCESS_LOGOUT: 'PROCESS_LOGOUT',
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  GET_ACCESS_TOKEN: 'GET_ACCESS_TOKEN',
  GET_REFRESH_TOKEN: 'GET_REFRESH_TOKEN',
  GET_GOOGLE_USER_INFO: 'GET_GOOGLE_USER_INFO',

  // admin =========

  // video =========
  GET_VIDEO_SUCCESS: 'GET_VIDEO_SUCCESS',
  GET_VIDEO_FALSE: 'GET_VIDEO_FALSE',
  SEARCH_VIDEO_SUCCESS: 'SEARCH_VIDEO_SUCCESS',
  SHORT_VIDEO_SUCCESS: 'SHORT_VIDEO_SUCCESS',
  WATCH_VIDEO_SUCCESS: 'WATCH_VIDEO_SUCCESS',
  VIDEO_RELATED: 'VIDEO_RELATED',
  GET_CHANNEL_VIDEO: 'GET_CHANNEL_VIDEO',
  IS_SPINNER: 'IS_SPINNER',
  IS_LOADING_BAR: 'IS_LOADING_BAR',
  CURRENT_PAGE: 'CURRENT_PAGE',
  RESET_MESSAGE: 'RESET_MESSAGE',
  SET_FIRST_SHORT_VIDEO: 'SET_FIRST_SHORT_VIDEO',
  // playlist
  GET_PLAYLIST_PRIVATE: 'GET_PLAYLIST_PRIVATE',
  GET_PLAYLIST_PUBLIC: 'GET_PLAYLIST_PUBLIC',
  // trending
  GET_TRENDING: 'GET_TRENDING',
  // -- rate
  GET_RATE: 'GET_RATE',
  POST_RATE: 'POST_RATE',

  // -- subscription
  SUBSCRIPTIONS: 'SUBSCRIPTIONS',
  IS_CHANNEL_SUBSCRIBED: 'IS_CHANNEL_SUBSCRIBED',
  IS_SUBSCRIBED: 'IS_SUBSCRIBED',

  // -- comments
  GET_COMMENT_THREADS: 'GET_COMMENT_THREADS',
  GET_COMMENTS: 'GET_COMMENTS',
  POST_COMMENT: 'POST_COMMENT',
  DELETE_COMMENT: 'DELETE_COMMENT',

  // manager
  POST_VIDEO: 'POST_VIDEO',
  DELETE_VIDEO: 'DELETE_VIDEO',
  UPDATE_VIDEO: 'UPDATE_VIDEO',
  GET_MY_VIDEO: 'GET_MY_VIDEO',
  SET_UPLOADING_VIDEO: 'SET_UPLOADING_VIDEO',
  SET_UPLOAD_MODAL: 'SET_UPLOAD_MODAL',

  SET_CHANNEL_INFO: 'SET_CHANNEL_INFO',
});

export default actionTypes;
